#!/usr/bin/env python3
"""Generate deterministic clip-space vertex frames for the D3D12 cube."""
from pathlib import Path
import math
import struct
import sys

FRAMES = 32
FOV_SCALE = math.sqrt(3.0)
ASPECT = 640.0 / 480.0
NEAR, FAR = 1.0, 10.0

# Faces use counter-clockwise triangles before projection; culling is disabled.
faces = (
    ((-1, -1, -1), (-1, 1, -1), (1, 1, -1), (1, -1, -1), (0.91, 0.25, 0.20, 1)),
    ((1, -1, 1), (1, 1, 1), (-1, 1, 1), (-1, -1, 1), (0.18, 0.66, 0.94, 1)),
    ((-1, -1, 1), (-1, 1, 1), (-1, 1, -1), (-1, -1, -1), (0.95, 0.76, 0.19, 1)),
    ((1, -1, -1), (1, 1, -1), (1, 1, 1), (1, -1, 1), (0.25, 0.82, 0.38, 1)),
    ((-1, 1, -1), (-1, 1, 1), (1, 1, 1), (1, 1, -1), (0.67, 0.34, 0.91, 1)),
    ((-1, -1, 1), (-1, -1, -1), (1, -1, -1), (1, -1, 1), (0.94, 0.46, 0.17, 1)),
)

def transform(vertex, angle):
    x, y, z = vertex
    cy, sy = math.cos(angle), math.sin(angle)
    cx, sx = math.cos(angle * 0.63), math.sin(angle * 0.63)
    x, z = x * cy + z * sy, -x * sy + z * cy
    y, z = y * cx - z * sx, y * sx + z * cx
    z += 4.25
    return (x * FOV_SCALE / ASPECT, y * FOV_SCALE,
            z * FAR / (FAR - NEAR) - NEAR * FAR / (FAR - NEAR), z)

def generate():
    values = []
    order = (0, 1, 2, 0, 2, 3)
    for frame in range(FRAMES):
        angle = frame * 2.0 * math.pi / FRAMES
        for face in faces:
            color = face[4]
            for index in order:
                values.extend(transform(face[index], angle))
                values.extend(color)
    return struct.pack('<' + 'f' * len(values), *values)

def main():
    if len(sys.argv) != 2:
        raise SystemExit('usage: generate_vertices.py OUTPUT_HEADER')
    data = generate()
    target = Path(sys.argv[1])
    with target.open('w') as out:
        out.write('/* Generated by generate_vertices.py. */\n')
        out.write(f'#define CUBE_FRAME_COUNT {FRAMES}u\n')
        out.write('#define CUBE_VERTEX_COUNT 36u\n')
        out.write('#define CUBE_VERTEX_STRIDE 32u\n')
        out.write('static const unsigned char cube_frames[] = {\n')
        for start in range(0, len(data), 12):
            out.write('    ' + ', '.join(f'0x{x:02x}' for x in data[start:start + 12]) + ',\n')
        out.write('};\n')

if __name__ == '__main__':
    main()
