#!/usr/bin/env python3
"""Generate src/msvcrt-ctype.js from Wine's msvcrt ctype.c.

The two character-classification tables MSVCRT__ctype and MSVCRT__wctype are
part of msvcrt's exported data (_ctype/_wctype and, via __p__pctype /
__p__pwctype, __p__mbctype's pctype pointer). Wine builds msvcrt.dll with
_MSVCR_VER=0, which fixes the three version-dependent entries
(B110=_BLANK, D120=4, S140=L140=C140=0).
"""
import re
import sys
import urllib.request

SOURCE = ("https://raw.githubusercontent.com/wine-mirror/wine/"
          "db11d0fe6a169c457e23d007e20404643d067aa8/dlls/msvcrt/ctype.c")
OUT = "src/msvcrt-ctype.js"

ABBREVIATIONS = {"_C_": 0x20, "_S_": 0x08, "_P_": 0x10, "_D_": 0x04,
                 "_H_": 0x80, "_U_": 0x01, "_L_": 0x02, "_BLANK": 0x40,
                 "B110": 0x40, "D120": 0x04, "S140": 0, "L140": 0, "C140": 0}


def extract(text, name):
    start = text.index(name)
    opening = text.index('{', start)
    depth = 0
    for index in range(opening, len(text)):
        if text[index] == '{':
            depth += 1
        elif text[index] == '}':
            depth -= 1
            if depth == 0:
                body = text[opening + 1:index]
                break
    else:
        raise SystemExit(f"unterminated initializer for {name}")
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    values = []
    for token in body.replace('\n', ' ').split(','):
        token = token.strip()
        if not token:
            continue
        values.append(evaluate(token))
    return values


def evaluate(expression):
    """Resolve one initializer: a literal, an abbreviation, or a bit-or of them."""
    for name, value in ABBREVIATIONS.items():
        expression = re.sub(rf'\b{re.escape(name)}\b', str(value), expression)
    if not re.fullmatch(r'[0-9a-fA-FxX|+\s]+', expression):
        raise SystemExit(f"unsupported initializer {expression!r}")
    return eval(expression)  # noqa: S307 - restricted to digits and bit-or


def main():
    with urllib.request.urlopen(SOURCE) as response:
        text = response.read().decode()
    ctype = extract(text, 'MSVCRT__ctype [257]')
    wctype = extract(text, 'MSVCRT__wctype[257]')
    for table in (ctype, wctype):
        if len(table) != 257:
            raise SystemExit(f"expected 257 entries, got {len(table)}")
        if any(value < 0 or value > 0xffff for value in table):
            raise SystemExit("table entry out of range")

    def rows(table):
        lines = []
        for index in range(0, 257, 12):
            chunk = ', '.join(f'0x{value:04x}' for value in table[index:index + 12])
            lines.append(f'  {chunk},')
        return '\n'.join(lines)

    module = f"""// Generated by scripts/build-msvcrt-ctype.py. Do not edit by hand.
//
// Wine 11.0 dlls/msvcrt/ctype.c builds msvcrt.dll with _MSVCR_VER=0, so the
// version-dependent entries resolve to B110=_BLANK, D120=_HEX and
// S140=L140=C140=0. The tables are the exported classification data itself
// (_ctype/_wctype), not a reimplementation.
export const CTYPE_TABLE = Uint16Array.from([
{rows(ctype)}
]);

export const WCTYPE_TABLE = Uint16Array.from([
{rows(wctype)}
]);
"""
    with open(OUT, 'w') as handle:
        handle.write(module)
    print(f"wrote {OUT}: ctype[66]=0x{ctype[66]:04x} wctype[66]=0x{wctype[66]:04x}")


if __name__ == '__main__':
    sys.exit(main())
