#!/usr/bin/env python3
"""Generate the msvcrt.dll export name list from Wine's own spec file.

A statically linked MSVC program, or a packer that walks its CRT import table at
run time, resolves these names through GetProcAddress and aborts when one is
missing. Reproducing the real export surface is what lets such a program run;
this script pins the list to a specific Wine revision so it is auditable rather
than hand-written.

Usage:
  python3 scripts/generate-msvcrt-exports.py [path/to/msvcrt.spec]

With no argument the pinned spec is downloaded and its SHA-256 verified.
"""
from pathlib import Path
import hashlib
import re
import sys
import urllib.request

REVISION = "db11d0fe6a169c457e23d007e20404643d067aa8"
URL = f"https://raw.githubusercontent.com/wine-mirror/wine/{REVISION}/dlls/msvcrt/msvcrt.spec"
SHA256 = "a7bfcc2c05265bf6304300f62c46a63beda3eed5e79354d16185593d95c5866a"

ROOT = Path(__file__).resolve().parents[1]


def spec_text(supplied):
    if supplied:
        return Path(supplied).read_text(), str(Path(supplied))
    cache = ROOT / ".cache" / "wine-msvcrt.spec"
    if not cache.exists():
        cache.parent.mkdir(parents=True, exist_ok=True)
        urllib.request.urlretrieve(URL, cache)
    text = cache.read_text()
    digest = hashlib.sha256(text.encode()).hexdigest()
    if SHA256 and digest != SHA256:
        raise SystemExit(f"pinned msvcrt.spec SHA-256 mismatch: {digest}")
    return text, str(cache)


def names(text):
    """Ordered, de-duplicated export names, C entry points only."""
    result = []
    seen = set()
    for line in text.split("\n"):
        raw = line.strip()
        if not raw or raw.startswith("#"):
            continue
        if raw.startswith("@"):
            raw = raw[1:].strip()
        else:
            match = re.match(r"^\d+\s+(.*)$", raw)
            if not match:
                continue
            raw = match.group(1)
        raw = re.sub(r"^(cdecl|stdcall|thiscall)\s+", "", raw)
        while True:
            match = re.match(r"^(-[\w=]+|-arch=\w+)\s+", raw)
            if not match:
                break
            raw = raw[match.end():]
        extern = re.match(r"^extern\s+(\S+)\s+(\S+)$", raw)
        if extern:
            name, alias = extern.group(1), extern.group(2)
        else:
            match = re.match(r"^(\S+?)(?:\(|$)", raw)
            if not match:
                continue
            name, alias = match.group(1), None
        # C++ mangled names are never resolved by a C program or by the
        # packers these probes exercise, and Wine exports them at the same
        # ordinals as the C names they decorate.
        if name.startswith("?") or not name or len(name) > 96:
            continue
        if name in seen:
            continue
        seen.add(name)
        result.append((name, alias))
    return result


text, source = spec_text(sys.argv[1] if len(sys.argv) > 1 else None)
entries = names(text)
names_only = [name for name, _ in entries]
aliases = {name: alias for name, alias in entries if alias}

out = ROOT / "src" / "msvcrt-exports.js"
out.write_text(
    "// Generated by scripts/generate-msvcrt-exports.py from Wine's msvcrt.spec\n"
    f"// at revision {REVISION}. Do not edit by hand.\n"
    "// The name list is the real CRT export surface; an entry's handler is\n"
    "// supplied by src/msvcrt.js when the runtime implements it and is otherwise\n"
    "// an explicit trap, so no name resolves to a silent no-op.\n"
    "export const MSVCRT_EXPORT_NAMES = Object.freeze([\n"
    + "".join(f"  {name!r},\n" for name in names_only)
    + "]);\n\n"
    "export const MSVCRT_EXPORT_ALIASES = Object.freeze({\n"
    + "".join(f"  {name!r}: {alias!r},\n" for name, alias in sorted(aliases.items()))
    + "});\n"
)
print(f"wrote {len(names_only)} names ({len(aliases)} aliases) to {out.relative_to(ROOT)}")
