#!/usr/bin/env python3
"""Generate the msvcrt.dll export name list from Wine's own spec file.

A statically linked MSVC program, or a packer that walks its CRT import table at
run time, resolves these names through GetProcAddress and aborts when one is
missing. Reproducing the real export surface is what lets such a program run;
this script pins the list to a specific Wine revision so it is auditable rather
than hand-written.

Usage:
  python3 scripts/generate-msvcrt-exports.py [path/to/msvcrt.spec]

With no argument the pinned spec is downloaded and its SHA-256 verified.
"""
from pathlib import Path
import hashlib
import re
import sys
import urllib.request

REVISION = "db11d0fe6a169c457e23d007e20404643d067aa8"
URL = f"https://raw.githubusercontent.com/wine-mirror/wine/{REVISION}/dlls/msvcrt/msvcrt.spec"
SHA256 = "a7bfcc2c05265bf6304300f62c46a63beda3eed5e79354d16185593d95c5866a"

ROOT = Path(__file__).resolve().parents[1]


def spec_text(supplied):
    if supplied:
        return Path(supplied).read_text(), str(Path(supplied))
    cache = ROOT / ".cache" / "wine-msvcrt.spec"
    if not cache.exists():
        cache.parent.mkdir(parents=True, exist_ok=True)
        urllib.request.urlretrieve(URL, cache)
    text = cache.read_text()
    digest = hashlib.sha256(text.encode()).hexdigest()
    if SHA256 and digest != SHA256:
        raise SystemExit(f"pinned msvcrt.spec SHA-256 mismatch: {digest}")
    return text, str(cache)


def names(text):
    """Ordered, de-duplicated exports with their calling convention.

    A declaration is ``@ <convention> [-modifiers] <name> [(args)] [alias]``.
    ``extern`` marks a data symbol whose real (decorated) name follows it. The
    convention matters: a handler that pops its own arguments (stdcall) for a
    cdecl entry corrupts the caller's stack, so the runtime must return the
    documented convention for each name.
    """
    result = []
    seen = set()
    for line in text.split("\n"):
        raw = line.strip()
        if not raw or raw.startswith("#"):
            continue
        m = re.match(r"^(?:\d+\s+|@\s+)(.*)$", raw)
        if not m:
            continue
        body = m.group(1)
        convention = "stdcall"
        for candidate in ("cdecl", "stdcall", "thiscall", "varargs"):
            if re.match(rf"^{candidate}(?=\s|\()", body):
                convention = candidate
                body = body[len(candidate):].strip()
                break
        data = False
        if re.match(r"^extern(?=\s|\()", body):
            data = True
            body = body[len("extern"):].strip()
        while True:
            modifier = re.match(r"^(-[\w=!]+)\s+", body)
            if not modifier:
                break
            body = body[modifier.end():]
        token = body.split()[0] if body.split() else ""
        name = token.split("(")[0]
        if name.startswith("?") or not name or len(name) > 120:
            continue  # C++ mangled names are never resolved by a C program.
        if name in seen:
            continue
        seen.add(name)
        # varargs and cdecl both leave argument cleanup to the caller.
        result.append((name, "cdecl" if convention in ("cdecl", "varargs") else "stdcall", data))
    return result


text, source = spec_text(sys.argv[1] if len(sys.argv) > 1 else None)
entries = names(text)

out = ROOT / "src" / "msvcrt-exports.js"
cdecl = sorted(name for name, convention, _ in entries if convention == "cdecl")
data = sorted(name for name, _, is_data in entries if is_data)
out.write_text(
    "// Generated by scripts/generate-msvcrt-exports.py from Wine's msvcrt.spec\n"
    f"// at revision {REVISION}. Do not edit by hand.\n"
    "// Every C export name resolves; a name whose handler the runtime does not\n"
    "// implement traps explicitly instead of succeeding silently. The convention\n"
    "// split is required: a stdcall handler for a cdecl entry would pop arguments\n"
    "// the caller also pops, corrupting the stack.\n"
    "export const MSVCRT_EXPORT_NAMES = Object.freeze([\n"
    + "".join(f"  {name!r},\n" for name, _, _ in entries)
    + "]);\n\n"
    "// Entries declared cdecl (or varargs, which is cdecl in the i386 ABI).\n"
    "export const MSVCRT_CDECL_EXPORTS = Object.freeze(new Set([\n"
    + "".join(f"  {name!r},\n" for name in cdecl)
    + "]));\n\n"
    "// Data exports: GetProcAddress must return the address of the storage the\n"
    "// provider materializes, not a code thunk.\n"
    "export const MSVCRT_DATA_EXPORTS = Object.freeze(new Set([\n"
    + "".join(f"  {name!r},\n" for name in data)
    + "]));\n"
)
print(
    f"wrote {len(entries)} names ({len(cdecl)} cdecl, {len(data)} data) to "
    f"{out.relative_to(ROOT)}"
)
