"""Independent Decimal oracle for finite F2XM1 results, not runtime code."""
from decimal import Decimal, localcontext, ROUND_HALF_EVEN, ROUND_CEILING, ROUND_FLOOR
from pathlib import Path
import json
import random

J = 1 << 63

def raw(sig, exponent, negative=False):
    return (sig.to_bytes(8, 'little') + (exponent | (0x8000 if negative else 0)).to_bytes(2, 'little')).hex()

def value(sig, exponent, negative=False):
    return Decimal(-sig if negative else sig) * Decimal(2) ** ((exponent or 1) - 16383 - 63)

def rounded(result, mode, inexact):
    negative = result < 0
    magnitude = abs(result)
    if not magnitude:
        return raw(0, 0, negative), 0, False
    numerator, denominator = magnitude.as_integer_ratio()
    exponent = numerator.bit_length() - denominator.bit_length()
    if magnitude < Decimal(2) ** exponent:
        exponent -= 1
    scaled = magnitude / (Decimal(2) ** max(exponent - 63, -16445))
    rounding = [ROUND_HALF_EVEN, ROUND_CEILING if negative else ROUND_FLOOR,
                ROUND_FLOOR if negative else ROUND_CEILING, ROUND_FLOOR][mode]
    significand = int(scaled.to_integral_value(rounding=rounding))
    inexact = inexact or scaled != significand
    up = significand > scaled
    if significand >= 2 * J:
        significand >>= 1
        exponent += 1
    if exponent > 16383:
        infinite = mode == 0 or (mode == 1 and negative) or (mode == 2 and not negative)
        return raw(J if infinite else 2 * J - 1, 0x7fff if infinite else 0x7ffe, negative), 0x28, infinite
    field = exponent + 16383 if exponent >= -16382 else int(significand >= J)
    return raw(significand, field, negative), (0x20 if inexact else 0) | (0x10 if inexact and field == 0 else 0), up

# Arguments strictly inside the documented F2XM1 domain (-1, 1).
cases = [
    ('one', (J, 16383, False)),                      # +1
    ('minus-one', (J, 16383, True)),                 # -1
    ('half', (J, 16382, False)),                     # +0.5
    ('minus-half', (J, 16382, True)),                # -0.5
    ('quarter', (J, 16381, False)),                  # +0.25
    ('minus-quarter', (J, 16381, True)),             # -0.25
    ('just-below-one', (2 * J - 1, 16382, False)),   # largest value < 1
    ('just-above-minus-one', (2 * J - 1, 16382, True)),
    ('small', (J, 16300, False)),                    # ~2^-83
    ('minus-small', (J, 16300, True)),
    ('tiny-subnormal', (1, 0, False)),               # smallest subnormal
    ('minus-tiny-subnormal', (1, 0, True)),
    ('three-quarters', (3 * J // 2, 16382, False)),
    ('minus-three-quarters', (3 * J // 2, 16382, True)),
]
rng = random.Random(0xF2A1B3C5)
for i in range(40):
    # Random significand in [J, 2J) with an exponent giving |x| < 1.
    cases.append((f'random-{i}', (rng.randrange(J, 2 * J), rng.randrange(1, 16383), bool(rng.randrange(2)))))

vectors = []
with localcontext() as ctx:
    ctx.prec = 400
    ln2 = Decimal(2).ln()
    for name, (sig, exponent, negative) in cases:
        x = value(sig, exponent, negative)
        if not (abs(x) < 1):
            continue
        # 2^x - 1 = expm1(x ln 2). Decimal has no expm1, so subtract 1 with
        # enough extra precision to keep the small-argument difference exact.
        ctx.prec = 400 + max(0, int((16383 - (exponent or 1)) * 0.302)) + 80
        result = (x * ln2).exp() - 1
        inexact = True  # 2^x - 1 is irrational for every nonzero binary rational x
        denormal = 2 if exponent == 0 else 0
        for mode in range(4):
            output, flags, up = rounded(result, mode, inexact)
            vectors.append(dict(name=name, x=raw(sig, exponent, negative), mode=mode,
                                output=output, flags=flags | denormal, roundedUp=up))
output = Path(__file__).resolve().parents[1] / 'tests/fixtures/x87-exp-vectors.json'
output.write_text(json.dumps({'oracle': 'Python Decimal, up to ~400+ decimal digits; deterministic inputs; |x| < 1', 'vectors': vectors}, indent=2) + '\n')
header = output.parent / 'x87' / 'exp-vectors.h'
header.parent.mkdir(exist_ok=True)
def cbytes(text):
    return '{' + ','.join(f'0x{b:02x}' for b in bytes.fromhex(text)) + '}'
header.write_text('// Generated by scripts/generate-x87-exp-vectors.py.\n'
    'static const struct Vector { BYTE x[10], output[10]; WORD control, status; } vectors[] = {\n'
    + ''.join('    {' + ', '.join([cbytes(v['x']), cbytes(v['output']),
              hex(0x037f | (v['mode'] << 10)), hex(v['flags'] | (0x200 if v['roundedUp'] else 0))]) + '},\n' for v in vectors)
    + '};\n')
print(f'wrote {len(vectors)} vectors')
