"""Independent Decimal oracle for finite FYL2X results, not runtime code."""
from decimal import Decimal, localcontext, ROUND_HALF_EVEN, ROUND_CEILING, ROUND_FLOOR
from pathlib import Path
import json
import random

J = 1 << 63

def raw(sig, exponent, negative=False):
    return (sig.to_bytes(8, 'little') + (exponent | (0x8000 if negative else 0)).to_bytes(2, 'little')).hex()

def value(sig, exponent, negative=False):
    return Decimal(-sig if negative else sig) * Decimal(2) ** ((exponent or 1) - 16383 - 63)

def rounded(result, mode, inexact_log):
    negative = result < 0
    magnitude = abs(result)
    if not magnitude:
        return raw(0, 0, negative), 0, False
    numerator, denominator = magnitude.as_integer_ratio()
    exponent = numerator.bit_length() - denominator.bit_length()
    if magnitude < Decimal(2) ** exponent:
        exponent -= 1
    scaled = magnitude / (Decimal(2) ** max(exponent - 63, -16445))
    rounding = [ROUND_HALF_EVEN, ROUND_CEILING if negative else ROUND_FLOOR,
                ROUND_FLOOR if negative else ROUND_CEILING, ROUND_FLOOR][mode]
    significand = int(scaled.to_integral_value(rounding=rounding))
    inexact = scaled != significand or inexact_log
    up = significand > scaled
    if significand >= 2 * J:
        significand >>= 1
        exponent += 1
    if exponent > 16383:
        infinite = mode == 0 or (mode == 1 and negative) or (mode == 2 and not negative)
        return raw(J if infinite else 2 * J - 1, 0x7fff if infinite else 0x7ffe, negative), 0x28, infinite
    field = exponent + 16383 if exponent >= -16382 else int(significand >= J)
    return raw(significand, field, negative), (0x20 if inexact else 0) | (0x10 if inexact and field == 0 else 0), up

cases = [
    ('three', (3 * J // 2, 16384, False), (J, 16383, False)),
    ('above-one', (J + 1, 16383, False), (J, 16383, False)),
    ('below-one', (2 * J - 1, 16382, False), (J, 16383, False)),
    ('far-exponent', (J + 7919, 30000, False), (J + 111, 12345, True)),
    ('smallest-subnormal', (1, 0, False), (J, 16383, False)),
    ('subnormal-multiplier', (3 * J // 2, 16383, False), (1, 0, False)),
    ('tiny-result', (J + 1, 16383, False), (J, 1, True)),
    ('overflow', (J, 16385, False), (2 * J - 1, 0x7ffe, False)),
    ('negative-overflow', (J, 16385, False), (2 * J - 1, 0x7ffe, True)),
    ('exact-fraction', (J, 16380, False), (3 * J // 2, 16383, False)),
    ('log-negative-product', (J, 16381, False), (J, 16382, True)),
]
rng = random.Random(0x19870387)
for i in range(40):
    cases.append((f'random-{i}', (rng.randrange(J, 2*J), rng.randrange(1, 0x7fff), False),
                  (rng.randrange(J, 2*J), rng.randrange(1, 0x7fff), bool(rng.randrange(2)))))
vectors = []
with localcontext() as ctx:
    ctx.prec = 320
    ln2 = Decimal(2).ln()
    for name, x, y in cases:
        inexact_log = bool(x[0] & (x[0] - 1))
        logarithm = value(*x).ln() / ln2 if inexact_log else Decimal(x[0].bit_length() - 1 + (x[1] or 1) - 16383 - 63)
        result = logarithm * value(*y)
        denormal = 2 if any(exponent == 0 and sig and sig < J for sig, exponent, _ in (x, y)) else 0
        for mode in range(4):
            output, flags, up = rounded(result, mode, inexact_log)
            vectors.append(dict(name=name, x=raw(*x), y=raw(*y), mode=mode, output=output, flags=flags | denormal, roundedUp=up))
output = Path(__file__).resolve().parents[1] / 'tests/fixtures/x87-log-vectors.json'
output.write_text(json.dumps({'oracle': 'Python Decimal, 320 decimal digits; deterministic inputs; finite positive x', 'vectors': vectors}, indent=2) + '\n')
header = output.parent / 'x87' / 'log-vectors.h'
header.parent.mkdir(exist_ok=True)
def cbytes(text):
    return '{' + ','.join(f'0x{b:02x}' for b in bytes.fromhex(text)) + '}'
header.write_text('// Generated by scripts/generate-x87-log-vectors.py.\n'
    'static const struct Vector { BYTE x[10], y[10], output[10]; WORD control, status; } vectors[] = {\n'
    + ''.join('    {' + ', '.join([cbytes(v['x']), cbytes(v['y']), cbytes(v['output']),
              hex(0x037f | (v['mode'] << 10)), hex(v['flags'] | (0x200 if v['roundedUp'] else 0))]) + '},\n' for v in vectors)
    + '};\n')
