"""Generate PE32 Vulkan offsets and stdcall stack widths with the actual Windows compiler."""
from pathlib import Path
import json
import re
import struct
import subprocess
import tempfile
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
HEADERS = ROOT / '.cache/vulkan-headers'
registry = ET.parse(HEADERS / 'registry/vk.xml').getroot()
names = '''VkApplicationInfo VkInstanceCreateInfo VkDeviceCreateInfo VkDeviceQueueCreateInfo
VkPhysicalDeviceProperties VkPhysicalDeviceLimits VkPhysicalDeviceFeatures
VkPhysicalDeviceMemoryProperties VkMemoryType VkMemoryHeap VkQueueFamilyProperties
VkFormatProperties VkSurfaceCapabilitiesKHR VkSurfaceFormatKHR VkExtensionProperties
VkWin32SurfaceCreateInfoKHR VkSwapchainCreateInfoKHR VkMemoryAllocateInfo VkMemoryRequirements
VkBufferCreateInfo VkImageCreateInfo VkImageViewCreateInfo VkImageSubresourceLayout VkSubresourceLayout
VkImageSubresource VkImageSubresourceRange VkImageMemoryBarrier VkBufferMemoryBarrier
VkShaderModuleCreateInfo VkPipelineShaderStageCreateInfo VkGraphicsPipelineCreateInfo
VkPipelineVertexInputStateCreateInfo VkPipelineInputAssemblyStateCreateInfo
VkPipelineRasterizationStateCreateInfo VkPipelineColorBlendStateCreateInfo
VkPipelineColorBlendAttachmentState VkPipelineDepthStencilStateCreateInfo
VkPipelineViewportStateCreateInfo VkPipelineMultisampleStateCreateInfo
VkPipelineDynamicStateCreateInfo VkPipelineLayoutCreateInfo VkPipelineCacheCreateInfo
VkDescriptorSetLayoutCreateInfo VkDescriptorSetLayoutBinding VkDescriptorPoolCreateInfo
VkDescriptorSetAllocateInfo VkWriteDescriptorSet VkDescriptorImageInfo VkDescriptorBufferInfo
VkSamplerCreateInfo VkRenderPassCreateInfo VkAttachmentDescription VkAttachmentReference
VkSubpassDescription VkFramebufferCreateInfo VkCommandPoolCreateInfo VkCommandBufferAllocateInfo
VkCommandBufferBeginInfo VkRenderPassBeginInfo VkSubmitInfo VkPresentInfoKHR VkFenceCreateInfo
VkSemaphoreCreateInfo VkViewport VkRect2D VkOffset2D VkExtent2D VkBufferImageCopy
VkVertexInputBindingDescription VkVertexInputAttributeDescription VkBufferCopy VkPushConstantRange
VkMappedMemoryRange VkComputePipelineCreateInfo'''.split()
types = {t.get('name', t.findtext('name')): t for t in registry.findall('./types/type')}
names = [n for n in names if n in types]
expressions = []
layouts = {}
for name in names:
    fields = ['__size'] + [m.findtext('name') for m in types[name].findall('member')]
    layouts[name] = fields
    expressions.extend([f'sizeof({name})'] + [f'offsetof({name}, {field})' for field in fields[1:]])
with tempfile.TemporaryDirectory() as tmp:
    temp = Path(tmp)
    (temp / 'layout.c').write_text('#define VK_USE_PLATFORM_WIN32_KHR\n#include <stddef.h>\n#include <vulkan/vulkan.h>\nconst unsigned int __attribute__((section(".vkabi"))) offsets[] = {' + ','.join(expressions) + '};\n')
    subprocess.run(['i686-w64-mingw32-gcc', '-I', str(HEADERS / 'include'), '-c', str(temp / 'layout.c'), '-o', str(temp / 'layout.o')], check=True)
    subprocess.run(['i686-w64-mingw32-objcopy', '-O', 'binary', '--only-section=.vkabi', str(temp / 'layout.o'), str(temp / 'layout.bin')], check=True)
    data = (temp / 'layout.bin').read_bytes()
values = iter(struct.unpack('<' + 'I' * len(expressions), data[:4 * len(expressions)]))
layouts = {name: {field: next(values) for field in fields} for name, fields in layouts.items()}
dispatch = {name for name, node in types.items() if node.get('category') == 'handle' and 'VK_DEFINE_HANDLE' in ''.join(node.itertext())}
non_dispatch = {name for name, node in types.items() if node.get('category') == 'handle'} - dispatch
wide = non_dispatch | {'VkDeviceSize', 'VkDeviceAddress', 'uint64_t', 'int64_t'}
commands = {}
for node in registry.findall('./commands/command'):
    name = node.findtext('proto/name')
    if not name:
        continue
    params = [p for p in node.findall('param') if not p.get('api') or 'vulkan' in p.get('api').split(',')]
    widths = [2 if p.findtext('type') in wide and '*' not in ''.join(p.itertext()) else 1 for p in params]
    commands[name] = widths
text = '// Generated by scripts/generate-vulkan-abi.py against pinned Vulkan-Headers.\n'
text += 'export const VK_ABI = ' + json.dumps(layouts, indent=2) + ';\n'
# Keep signatures for the demo closure plus the loader entry points.
closure = set(re.findall(r'PFN_(vk\w+)', (ROOT / 'demos/vkcube/upstream/cube_functions.h').read_text()))
closure |= {'vkEnumerateInstanceVersion', 'vkGetFenceStatus', 'vkQueueWaitIdle', 'vkFlushMappedMemoryRanges', 'vkInvalidateMappedMemoryRanges'}
closure |= set(re.findall(r'impl\.(vk\w+)', (ROOT / 'src/vulkan.js').read_text()))
closure |= {'vkCmdBindVertexBuffers', 'vkCmdBindIndexBuffer', 'vkCmdDrawIndexed', 'vkCmdCopyBuffer', 'vkCmdPushConstants', 'vkCreateComputePipelines', 'vkCmdDispatch'}
text += 'export const VK_COMMANDS = ' + json.dumps({n: commands[n] for n in sorted(closure) if n in commands}, indent=2) + ';\n'
(ROOT / 'src/vulkan-abi.js').write_text(text)
print('Generated', len(layouts), 'struct layouts and', len(closure), 'signatures')
