#!/usr/bin/env python3
"""Generate the versioned Visual C++ runtime export surface from Wine's specs.

An application built against msvcr70..msvcr120 imports those names directly and
a program that resolves them at run time through GetProcAddress aborts when one
is missing, so the union of every versioned spec is the surface the runtime has
to answer.

The calling convention is not optional information. The i386 ABI has the callee
pop arguments for stdcall and the caller for cdecl, and the two are
indistinguishable from the name alone: the unusual decorated forms such as
`??2@YAPAXI@Z` carry no `@<bytes>` suffix even though operator new is cdecl, so
a name-only list silently dispatches C++ allocation as stdcall and removes four
bytes the caller also removes. Every entry therefore records the convention its
spec declares, and the runtime returns the same convention to the dispatcher.

Usage:
  python3 scripts/generate-msvcrt-versioned-exports.py [wine/dlls/directory]

With no argument the pinned Wine tree is used.
"""
from pathlib import Path
import hashlib
import re
import sys

REVISION = "db11d0fe6a169c457e23d007e20404643d067aa8"
VERSIONS = ["msvcr70", "msvcr71", "msvcr80", "msvcr90", "msvcr100", "msvcr110", "msvcr120"]
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TREE = ROOT / ".cache" / f"wine-{REVISION}"

# A declaration is `@ <convention> [-modifiers] <name> [(args)] [alias]`, an
# `extern` prefix marks a data symbol, and the leading ordinal form is ignored.
DECLARATION = re.compile(r"^(?:\d+\s+|@\s+)(?P<body>.*)$")
CONVENTIONS = ("cdecl", "stdcall", "thiscall", "varargs")


def parse_spec(path):
    """Ordered `{name: ('cdecl'|'stdcall', is_data)}` for one spec file."""
    entries = {}
    for line in path.read_text(errors="replace").split("\n"):
        raw = line.strip()
        if not raw or raw.startswith("#"):
            continue
        declaration = DECLARATION.match(raw)
        if not declaration:
            continue
        body = declaration.group("body")
        convention = "stdcall"
        for candidate in CONVENTIONS:
            if re.match(rf"^{candidate}(?=\s|\()", body):
                # varargs is cdecl in the i386 ABI: the caller removes the
                # arguments in both cases.
                convention = "cdecl" if candidate in ("cdecl", "varargs") else "stdcall"
                body = body[len(candidate) :].strip()
                break
        data = False
        if re.match(r"^extern(?=\s|\()", body):
            data = True
            body = body[len("extern") :].strip()
        while True:
            modifier = re.match(r"^(-[\w=!]+)\s+", body)
            if not modifier:
                break
            body = body[modifier.end() :]
        token = body.split()[0] if body.split() else ""
        name = token.split("(")[0]
        if not name or len(name) > 200:
            continue
        # The same name must never disagree across versions; a conflict would
        # make the union ambiguous and is reported rather than silently picked.
        if name in entries and entries[name][0] != convention:
            raise SystemExit(f"{path.name}: {name} is both {entries[name][0]} and {convention}")
        entries.setdefault(name, (convention, data))
    return entries


def main(tree):
    table = {}
    for version in VERSIONS:
        spec = tree / "dlls" / version / f"{version}.spec"
        if not spec.exists():
            raise SystemExit(f"missing spec: {spec}")
        for name, (convention, data) in parse_spec(spec).items():
            if name in table and table[name] != (convention, data):
                raise SystemExit(f"{name} disagrees between versioned specs")
            table.setdefault(name, (convention, data))
    names = sorted(table)
    cdecl = [name for name in names if table[name][0] == "cdecl"]
    data = [name for name in names if table[name][1]]
    out = ROOT / "src" / "msvcrt-versioned-exports.js"
    out.write_text(
        "// Generated by scripts/generate-msvcrt-versioned-exports.py from the\n"
        "// versioned Visual C++ runtime specs (msvcr70..msvcr120) at revision\n"
        f"// {REVISION}. Do not edit by hand.\n"
        "// These DLLs are supersets of msvcrt.dll; the union is registered for each\n"
        "// alias so a program built against any of them resolves every name, with a\n"
        "// real handler where the runtime has one and an explicit trap otherwise.\n"
        "export const VERSIONED_CRT_EXPORT_NAMES = Object.freeze([\n"
        + "".join(f"  {name!r},\n" for name in names)
        + "]);\n\n"
        "// Entries declared cdecl (or varargs, which is cdecl in the i386 ABI).\n"
        "// The decorated C++ names carry no @<bytes> suffix, so this list cannot be\n"
        "// derived from the names: operator new (`??2@YAPAXI@Z`) is cdecl and would\n"
        "// otherwise be dispatched stdcall, corrupting the caller's stack.\n"
        "export const VERSIONED_CRT_CDECL_EXPORTS = Object.freeze(new Set([\n"
        + "".join(f"  {name!r},\n" for name in cdecl)
        + "]));\n\n"
        "// Data exports: GetProcAddress must return the address of the storage the\n"
        "// provider materializes, not a code thunk.\n"
        "export const VERSIONED_CRT_DATA_EXPORTS = Object.freeze(new Set([\n"
        + "".join(f"  {name!r},\n" for name in data)
        + "]));\n"
    )
    digest = hashlib.sha256(out.read_bytes()).hexdigest()
    print(
        f"wrote {len(names)} names ({len(cdecl)} cdecl, {len(data)} data) to "
        f"{out.relative_to(ROOT)} sha256={digest[:16]}"
    )


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_TREE)
