#!/usr/bin/env python3
"""Generate contract destinations/export boundaries from verified Wine source."""
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import tarfile

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = json.loads((ROOT / "runtime/wine-base/manifest.json").read_text())
ARCHIVE = ROOT / "public/runtime/wine-base/wine-source.tar.gz"


def main():
    if hashlib.sha256(ARCHIVE.read_bytes()).hexdigest() != MANIFEST["sourceSha256"]:
        raise RuntimeError("Wine source archive hash mismatch")
    with tarfile.open(ARCHIVE) as archive:
        sources = {}
        for suffix in ["dlls/apisetschema/apisetschema.spec", "dlls/kernelbase/kernelbase.spec"]:
            member = next(m for m in archive if m.name.endswith("/" + suffix))
            sources[suffix] = archive.extractfile(member).read()
    schema = {}
    for line in sources["dlls/apisetschema/apisetschema.spec"].decode().splitlines():
        match = re.fullmatch(r"apiset ([a-z0-9-]+) =\s*([a-z0-9_.-]*)", line)
        if not match or match[1] in schema:
            raise RuntimeError(f"Unsupported/duplicate schema assignment: {line}")
        schema[match[1]] = match[2] or None
    exports = set()
    for line in sources["dlls/kernelbase/kernelbase.spec"].decode().splitlines():
        architecture = re.search(r"(?:^|\s)-arch=([^\s]+)", line)
        if architecture:
            names = architecture[1].lstrip("!").split(",")
            excluded = architecture[1].startswith("!")
            if ("i386" in names) == excluded:
                continue
        match = re.match(r"^\S+\s+(?:stdcall|cdecl|stub|extern)\s+(?:-\S+\s+)*([A-Za-z0-9_]+)", line)
        if match:
            exports.add(match[1])
    header = (
        "// Generated by scripts/generate-api-set-schema.py; do not edit.\n"
        f"// Wine {MANIFEST['sourceRevision']}; LGPL-2.1-or-later.\n"
        "// Corresponding full source/licenses: public/runtime/wine-base/.\n"
    )
    outputs = {
        "src/wine-api-set-schema.js": header + "export const WINE_API_SET_SCHEMA = " + json.dumps(schema, indent=2) + ";\n",
        "src/wine-kernelbase-exports.js": header + "export const WINE_KERNELBASE_EXPORTS = new Set(" + json.dumps(sorted(exports), indent=2) + ");\n",
        "runtime/wine/api-set-schema-manifest.json": json.dumps({
            "sourceRevision": MANIFEST["sourceRevision"],
            "sourceArchiveSha256": MANIFEST["sourceSha256"],
            "sourceFiles": {name: hashlib.sha256(data).hexdigest() for name, data in sources.items()},
            "contracts": len(schema),
            "destinations": len({v for v in schema.values() if v}),
            "unassignedContracts": sum(v is None for v in schema.values()),
            "kernelbaseExports": len(exports),
            "kernelbaseArchitecture": "i386",
        }, indent=2) + "\n",
    }
    for relative, source in outputs.items():
        formatted = subprocess.check_output(
            ["node", str(ROOT / "node_modules/prettier/bin/prettier.cjs"), "--stdin-filepath", relative],
            input=source, text=True, cwd=ROOT,
        )
        target = ROOT / relative
        if "--check" in sys.argv:
            if not target.is_file() or target.read_text() != formatted:
                raise RuntimeError(f"Generated schema differs: {relative}")
        else:
            target.write_text(formatted)
    print(f"Verified {len(schema)} Wine contracts and {len(exports)} KernelBase export names")


if __name__ == "__main__":
    main()
