"""Independent Decimal/Chudnovsky reference for native x87 trigonometric tests."""
from decimal import Decimal, localcontext, ROUND_HALF_EVEN, ROUND_CEILING, ROUND_FLOOR
from pathlib import Path
import json
import random

J = 1 << 63

def raw(sig, exponent, negative=False):
    return (sig.to_bytes(8, 'little') + (exponent | (0x8000 if negative else 0)).to_bytes(2, 'little')).hex()

def value(sig, exponent, negative=False):
    return Decimal(-sig if negative else sig) * Decimal(2) ** ((exponent or 1) - 16383 - 63)

def pi_chudnovsky():
    # Different series and arithmetic from the runtime's integer Machin bounds.
    m, l, x, k = 1, 13591409, 1, 6
    total = Decimal(l)
    for i in range(1, 40):
        m = m * (k**3 - 16*k) // i**3
        l += 545140134
        x *= -262537412640768000
        total += Decimal(m * l) / x
        k += 12
    return 426880 * Decimal(10005).sqrt() / total

def trig(x, cosine):
    term = Decimal(1) if cosine else x
    total = term
    index = 0 if cosine else 1
    for _ in range(1000):
        term *= -x*x / ((index + 1) * (index + 2))
        updated = total + term
        if total == updated:
            return total
        total = updated
        index += 2
    raise RuntimeError('Decimal reference did not converge')

def rounded(result, mode, denormal):
    negative = result.is_signed()
    magnitude = abs(result)
    numerator, denominator = magnitude.as_integer_ratio()
    exponent = numerator.bit_length() - denominator.bit_length()
    if magnitude < Decimal(2)**exponent:
        exponent -= 1
    scaled = magnitude / (Decimal(2)**max(exponent - 63, -16445))
    rounding = [ROUND_HALF_EVEN, ROUND_CEILING if negative else ROUND_FLOOR,
                ROUND_FLOOR if negative else ROUND_CEILING, ROUND_FLOOR][mode]
    significand = int(scaled.to_integral_value(rounding=rounding))
    up = significand > scaled
    if significand >= 2*J:
        significand >>= 1
        exponent += 1
    field = exponent + 16383 if exponent >= -16382 else int(significand >= J)
    return dict(output=raw(significand, field, negative), flags=0x20 | denormal | (0x10 if field == 0 else 0), roundedUp=up)

cases = [
    ('one', J, 16383, False), ('negative-one', J, 16383, True),
    ('half', J, 16382, False), ('tiny-boundary', J, 16319, False),
    ('below-tiny-boundary', 2*J-1, 16318, False),
    ('tiny-negative', J, 16000, True), ('minimum-normal', J, 1, False),
    ('largest-subnormal', J-1, 0, True), ('minimum-subnormal', 1, 0, False),
    ('negative-minimum-subnormal', 1, 0, True),
    ('largest-in-range', 2*J-1, 16445, False),
    ('negative-largest-in-range', 2*J-1, 16445, True),
]
for exponent in [16382,16383,16384,16385]:
    for delta in [-1,0,1]:
        cases.append((f'pi-neighbor-{exponent}-{delta}',0xc90fdaa22168c235+delta,exponent,False))
rng = random.Random(0x0387c05)
for i in range(32):
    cases.append((f'random-{i}',rng.randrange(J,2*J),rng.randrange(16310,16446),bool(rng.randrange(2))))
vectors = []
with localcontext() as ctx:
    ctx.prec = 450
    pi = pi_chudnovsky()
    for name, sig, exponent, negative in cases:
        # Tiny sin/cos differ from x/1 only at roughly 2*abs(binary exponent)
        # relative bits. Increase Decimal precision to retain that difference.
        ctx.prec = max(360, 180 + int(max(0,16383-(exponent or 1))*0.603) + 64)
        x = value(sig,exponent,negative)
        if abs(x) > 1:
            multiple = (x / (2*pi)).to_integral_value(rounding=ROUND_HALF_EVEN)
            x -= multiple * (2*pi)
        s, c = trig(x,False), trig(x,True)
        denormal = 2 if exponent == 0 else 0
        for mode in range(4):
            vectors.append(dict(name=name,x=raw(sig,exponent,negative),mode=mode,
                                sine=rounded(s,mode,denormal),cosine=rounded(c,mode,denormal)))
root = Path(__file__).resolve().parents[1] / 'tests/fixtures'
(root/'x87-trig-vectors.json').write_text(json.dumps(dict(oracle='Python Decimal Taylor series with Chudnovsky pi; 360+ decimal digits, adaptive for tiny arguments; mathematical sine/cosine',vectors=vectors),indent=2)+'\n')
def cbytes(text):
    return '{'+','.join(f'0x{b:02x}' for b in bytes.fromhex(text))+'}'
def status(result):
    return hex(result['flags'] | (0x200 if result['roundedUp'] else 0))
(root/'x87/trig-vectors.h').write_text('// Generated by scripts/generate-x87-trig-vectors.py.\n'
    'static const struct Vector { BYTE x[10], sine[10], cosine[10]; WORD control, sin_status, cos_status; } vectors[] = {\n'
    + ''.join('    {'+', '.join([cbytes(v['x']),cbytes(v['sine']['output']),cbytes(v['cosine']['output']),
               hex(0x037f | (v['mode'] << 10)),status(v['sine']),status(v['cosine'])])+'},\n' for v in vectors)
    + '};\n')
